const NFTS = [
    {
        "P":"BTC FRAT FRENS",
        "op":"MINT",
        "amt": "",
        "blk": "",
        "ref":"BFF_4",
        "desc":"3",
        "Hair":"BLACK",
        "Eye":"calm",
        "Nose":"round",
        "Mouth":"thinking",
        "Body":"Red Shirt",
        "Wall":"Cream",
        "bmp_key":"bff_3_4",
    },
    {
        "p": "BTC FRAT FRENS" ,
        "op": "mint" ,
        "tick": "BFF",
        "amt": "",
        "blk": "",
        "ref": "Bff_5",
        "desc": "3",
        " Hair": "yellow" ,
        "Eye": "surprise" ,
        "Nose": "oversized" ,
        "Mouth": "surprise" ,
        "Body": "red singlet" ,
        "Wall": "pink",
        "bmp_key": "bff_3_5",
        },
        {
            "p": "BTC FRAT FRENS" ,
            "op": "mint" ,
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref":"bff,_6" ,
            "desc":"3",
            " Hair":"bl,ack" ,
            "Eye": "shock" ,
            "Nose": "round" ,
            "Mouth": "surpris,e" ,
            "Body": "Yellow shirt," ,
            "Wall": "blue",
            "bmp_key": "bff,_3_5",
        },
        {
                "p": "BTC FRAT FRENS" ,
                "op": "mint" ,
                "tick": "BFF",
                "amt": "",
                "blk": "",
                "ref": "bff_7" ,
                "desc": "3",
                " Hair": "black" ,
                "Eye": "exciting" ,
                "Nose": "bean" ,
                "Mouth": "smiling" ,
                "Body": "purple shirt" ,
                "Wall": "sky blue",
                "bmp_key": "bff_3_7",
        },
        {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_8",
            "desc": "3",
            "Hair": "black",
            "Eye": "engross",
            "Nose": "doted",
            "Mouth": "open",
            "Body": "blue shirt",
            "Accessory": "cap",
            "Wall": "yellow",
            "bmp_key": "bff_3_8"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_9",
            "desc": "3",
            "Hair": "bewildered",
            "Eye": "wide eye",
            "Nose": "oversized",
            "Mouth": "gaping",
            "Body": "blue blazer",
            "Wall": "yellow",
            "bmp_key": "bff_3_9"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_8",
            "desc": "3",
            "Hair": "black",
            "Eye": "engross",
            "Nose": "oversized",
            "Mouth": "contented",
            "Body": "blue shirt",
            "Accessory": "cap",
            "Wall": "blue",
            "bmp_key": "bff_3_10"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_11",
            "desc": "3",
            "Hair": "bald",
            "Eye": "contemplative",
            "Nose": "bean",
            "Mouth": "relaxed",
            "Body": "blue shirt",
            "Wall": "orange",
            "bmp_key": "bff_3_11"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_12",
            "desc": "1",
            "Hair": "Black and white",
            "Eye": "",
            "Nose": "oversized",
            "Mouth": "open",
            "Body": "red jacket",
            "Accessory": "facecap",
            "Wall": "blue",
            "bmp_key": "bff_12"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_13",
            "desc": "3",
            "Hair": "black",
            "Eye": "covered",
            "Nose": "oversize",
            "Mouth": "talking",
            "Body": "red jacket",
            "Accessory": "face cap",
            "Wall": "light blue",
            "bmp_key": "bff_3_13"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_14",
            "desc": "3",
            "Hair": "black",
            "Eye": "neutral",
            "Nose": "pointed",
            "Mouth": "composed",
            "Body": "red singlet",
            "Accessory": "face cap",
            "Wall": "cream",
            "bmp_key": "bff_3_14"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_15",
            "desc": "3",
            "Hair": "yellow",
            "Eye": "alarmed",
            "Nose": "bean",
            "Mouth": "seren",
            "Body": "button shirt",
            "Wall": "",
            "bmp_key": "bff_3_15"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_16",
            "desc": "3",
            "Hair": "yellow",
            "Eye": "engross",
            "Nose": "oversized",
            "Mouth": "scowl",
            "Body": "red suit",
            "Wall": "yellow",
            "bmp_key": "bff_3_16"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_17",
            "desc": "4",
            "Hair": "Black",
            "Eye": "neutral",
            "Nose": "pointed",
            "Mouth": "calm",
            "Body": "red singlet",
            "Accessory": "cap",
            "Wall": "pink",
            "bmp_key": "bff_3_17"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_20",
            "desc": "3",
            "Hair": "covered",
            "Eye": "coverd",
            "Nose": "bean",
            "Mouth": "grimmacing",
            "Body": "purple shirt",
            "Accessory": "purple cap",
            "Wall": "blue",
            "bmp_key": "bff_3_20"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_21",
            "desc": "3",
            "Hair": "dread lock",
            "Eye": "tense",
            "Nose": "round",
            "Mouth": "seren",
            "Body": "button shirt",
            "Wall": "blue",
            "bmp_key": "bff_3_21"
          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint",
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_22",
            "desc": "3",
            "Hair": "black",
            "Eye": "furious",
            "Nose": "doted",
            "Mouth": "scowl",
            "Body": " red shirt",
            "Accessory": "brown cap",
            "Wall": "orange",
            "bmp_key":"bff_3_22"

          },
          {
            "p": "BTC FRAT FRENS",
            "op": "mint", 
            "tick": "BFF",
            "amt": "",
            "blk": "",
            "ref": "bff_22", 
            "desc": "3",
            " Hair": "covered", 
            "Eye": "covered", 
            "Nose": "pointed", 
            "Mouth": "grimace", 
            "Body": "black singlet", 
            "Accessory":"orange cap", 
            "Wall": "blue",
            "bmp_key": "bff_3_23",
            },
            {
                "p": "BTC FRAT FRENS",
                "op": "mint",
                "tick": "BFF",
                "amt": "",
                "blk": "",
                "ref": "bff_24",
                "desc": "3",
                "Hair": "black",
                "Eye": "curiosity",
                "Nose": "pointed",
                "Mouth": "gentle",
                "Body": "green shirt",
                "Accessory": "orange cap",
                "Wall": "blue",
                "bmp_key": "bff_3_24"
              },
              {
                "p": "BTC FRAT FRENS",
                "op": "mint",
                "tick": "BFF",
                "amt": "",
                "blk": "",
                "ref": "bff_25",
                "desc": "3",
                "Hair": "black",
                "Eye": "didain",
                "Nose": "oversize",
                "Mouth": "pressed",
                "Body": "shirtless",
                "Accessory": "cap",
                "Wall": "pink",
                "bmp_key": "bff_3_25"
              },
              {
                "p": "BTC FRAT FRENS",
                "op": "mint",
                "tick": "BFF",
                "amt": "",
                "blk": "",
                "ref": "bff_27",
                "desc": "3",
                "Hair": "black",
                "Eye": "open",
                "Nose": "bean",
                "Mouth": "open",
                "Body": "blue shirt",
                "Wall": "green",
                "bmp_key": "bff_3_27"
              },
              {
                "p": "BTC FRAT FRENS",
                "op": "mint",
                "tick": "BFF",
                "amt": "",
                "blk": "",
                "ref": "bff_28",
                "desc": "3",
                "Hair": "black",
                "Eye": "engross",
                "Nose": "pointed",
                "Mouth": "pressed",
                "Body": "red shirt",
                "Wall": "yellow",
                "bmp_key": "bff_3_28"
              }

];

export default NFTS;